defidev/defidev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tournois_foot.urls')),
]

defidev/tournois_foot/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import EquipeViewSet, JoueurViewSet, equipe_liste, creer_equipe, joueur_liste, creer_joueur, creer_match, \
    classement, MatchViewSet, recherche, RechercheViewSet

# Création du routeur DRF
router = DefaultRouter()
router.register(r'equipes', EquipeViewSet)
router.register(r'joueurs', JoueurViewSet)
router.register(r'matchs', MatchViewSet)
router.register(r'recherche', RechercheViewSet, basename='recherche')

urlpatterns = [
    # Routes API
    path('api/', include(router.urls)),

    # Routes pour les équipes
    path('equipes/', equipe_liste, name='equipe_liste'),
    path('creer-equipe/', creer_equipe, name='creer_equipe'),

    # Routes pour les joueurs
    path('joueurs/', joueur_liste, name='joueur_liste'),
    path('creer-joueur/', creer_joueur, name='creer_joueur'),

    #Routes pour les matchs
    path("creer-matchs/", creer_match, name="creer_match"),
    path("classement/", classement, name="classement"),

    #Route pour l'API de recherche
    path('recherche/', recherche, name='recherche'),
]

defidev/tournois_foot/models.py
from django.db import models
from django.core.exceptions import ValidationError
# Create your models here.
class Equipe(models.Model):
    nom = models.CharField(max_length=50)
    ville = models.CharField(max_length=100, default='Inconnu')
    buts_marques = models.PositiveIntegerField(default=0)
    buts_encaisses = models.PositiveIntegerField(default=0)
    points = models.PositiveIntegerField(default=0)

    def mettre_a_jour_stats(self):
        """Calcule les stats après chaque match."""
        matchs_domicile = self.matchs_domicile.all()
        matchs_exterieur = self.matchs_exterieur.all()

        self.buts_marques = sum(m.buts_domicile for m in matchs_domicile if m.equipe_domicile == self)
        self.buts_marques += sum(m.buts_exterieur for m in matchs_exterieur if m.equipe_exterieur == self)

        self.buts_encaisses = sum(m.buts_exterieur for m in matchs_domicile if m.equipe_domicile == self)
        self.buts_encaisses += sum(m.buts_domicile for m in matchs_exterieur if m.equipe_exterieur == self)

        self.points = sum(m.resultat().get(self, 0) for m in matchs_domicile | matchs_exterieur)

        self.save()

    def __str__(self):
        return f"{self.nom} - {self.points} pts"


class Joueur(models.Model):
    POSTE_CHOICES = [
        ('Gardien', 'Gardien'),
        ('Défenseur', 'Défenseur'),
        ('Milieu', 'Milieu'),
        ('Attaquant', 'Attaquant'),
    ]

    nom = models.CharField(max_length=50)
    poste = models.CharField(choices=POSTE_CHOICES)
    equipe = models.ForeignKey(Equipe, related_name='joueurs', on_delete=models.CASCADE)

    def clean(self):
        """Validation pour limiter à 11 joueurs par équipe"""
        if self.equipe and Joueur.objects.filter(equipe=self.equipe).count() >= 11:
            raise ValidationError(f"L'équipe {self.equipe.nom} a déjà 11 joueurs.")

    def save(self, *args, **kwargs):
        """Appelle la validation avant de sauvegarder"""
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nom

class Match(models.Model):
    id_match = models.AutoField(primary_key=True)
    equipe_domicile = models.ForeignKey(Equipe, on_delete=models.CASCADE, related_name="matchs_domicile", default='Inconnu')
    equipe_exterieur = models.ForeignKey(Equipe, on_delete=models.CASCADE, related_name="matchs_exterieur", default='Inconnu')
    buts_domicile = models.PositiveIntegerField(default=0)
    buts_exterieur = models.PositiveIntegerField(default=0)

    def resultat(self):
        """Détermine le résultat du match et retourne les points attribués."""
        if self.buts_domicile > self.buts_exterieur:
            return {self.equipe_domicile: 3, self.equipe_exterieur: 0}
        elif self.buts_domicile < self.buts_exterieur:
            return {self.equipe_domicile: 0, self.equipe_exterieur: 3}
        else:
            return {self.equipe_domicile: 1, self.equipe_exterieur: 1}

    def __str__(self):
        return f"{self.equipe_domicile.nom} {self.buts_domicile} - {self.buts_exterieur} {self.equipe_exterieur.nom}"

defidev/tournois_foot/forms.py
from django import forms
from .models import Equipe, Joueur, Match


class EquipeForm(forms.ModelForm):
    class Meta:
        model = Equipe
        fields = ['nom', 'ville']

class JoueurForm(forms.ModelForm):
    class Meta:
        model = Joueur
        fields = ['nom', 'poste', 'equipe']
        widgets = {
            'poste': forms.Select(choices=Joueur.POSTE_CHOICES, attrs={'class': 'form-control'}),
            'equipe': forms.Select(attrs={'class': 'form-control'}),
        }

class MatchForm(forms.ModelForm):
    class Meta:
        model = Match  # Spécifie le modèle 'Match'
        fields = ['equipe_domicile', 'equipe_exterieur', 'buts_domicile', 'buts_exterieur']

defidev/tournois_foot/views.py
from rest_framework.response import Response
from rest_framework import viewsets
from rest_framework.generics import ListCreateAPIView
from .models import Equipe, Joueur, Match
from .serializers import EquipeSerializer, JoueurSerializer, MatchSerializer, JoueurSearchSerializer, \
    EquipeSearchSerializer
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .forms import EquipeForm, JoueurForm, MatchForm
from django_elasticsearch_dsl.search import Search
from .documents import EquipeDocument, JoueurDocument
from elasticsearch_dsl import Q

class EquipeViewSet(viewsets.ModelViewSet):
    queryset = Equipe.objects.all()
    serializer_class = EquipeSerializer

class JoueurViewSet(viewsets.ModelViewSet):
    queryset = Joueur.objects.all()
    serializer_class = JoueurSerializer

class MatchViewSet(viewsets.ModelViewSet):
    queryset = Match.objects.all()
    serializer_class = MatchSerializer

class RechercheViewSet(viewsets.ViewSet):
    def list(self, request):
        query = request.GET.get('q', '')
        results = {'equipes': [], 'joueurs': []}

        if query:
            # Recherche dans les équipes
            search_equipes = Search(index='equipes').query('match', nom=query)
            equipes = [hit.to_dict() for hit in search_equipes.execute()]
            results['equipes'] = EquipeSearchSerializer(equipes, many=True).data

            # Recherche dans les joueurs (nom ou poste)
            search_joueurs = Search(index='joueurs').query(
                Q("bool", should=[
                    Q("match", nom=query),
                    Q("match", poste=query)
                ])
            )

            joueurs = [hit.to_dict() for hit in search_joueurs.execute()]
            results['joueurs'] = JoueurSearchSerializer(joueurs, many=True).data

        return Response(results)

def creer_equipe(request):
    if request.method == 'POST':
        form = EquipeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('equipe_liste')
    else:
        form = EquipeForm()
    return render(request, 'creer_equipe.html', {'form': form})

def equipe_liste(request):
    equipes = Equipe.objects.all()
    return render(request, 'equipe_liste.html', {'equipes': equipes})

def creer_joueur(request):
    if request.method == 'POST':
        form = JoueurForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('joueur_liste')
    else:
        form = JoueurForm()
    return render(request, 'creer_joueur.html', {'form': form})

def joueur_liste(request):
    joueurs = Joueur.objects.all()
    return render(request, 'joueur_liste.html', {'joueurs': joueurs})


def creer_match(request):
    """Affiche le formulaire et ajoute un match"""
    if request.method == "POST":
        form = MatchForm(request.POST)
        if form.is_valid():
            match = form.save()

            # Mise à jour des statistiques des équipes après chaque match
            match.equipe_domicile.mettre_a_jour_stats()
            match.equipe_exterieur.mettre_a_jour_stats()

            return redirect("classement")
    else:
        form = MatchForm()

    return render(request, "creer_match.html", {"form": form})

def classement(request):
    """Affiche la liste des matchs, triés par id_match."""
    matchs = Match.objects.all().order_by('id_match')
    return render(request, "classement.html", {"matchs": matchs})


def recherche(request):
    query = request.GET.get('q', '')
    results = {'equipes': [], 'joueurs': []}

    if query:
        # Recherche dans les équipes
        search_equipes = Search(index='equipes').query('match', nom=query)
        equipes = [hit.to_dict() for hit in search_equipes.execute()]
        results['equipes'] = equipes

        # Recherche dans les joueurs (nom ou poste)
        search_joueurs = Search(index='joueurs').query(
            Q("bool", should=[
                Q("match", nom=query),
                Q("match", poste=query),
                Q("match", equipe_nom=query)
            ])
        )
        joueurs = [hit.to_dict() for hit in search_joueurs.execute()]
        results['joueurs'] = joueurs

    return render(request, 'recherche.html', {'results': results, 'query': query})

defidev/tournois_foot/templates/classement.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}API Foot - Liste des Matchs{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="container mt-4">
    {% include 'includes/navbar.html' %}

    <div class="container mt-4">
        {% block content %}{% endblock %}
    </div>

    <h2>Liste des Matchs</h2>
    <table class="table table-striped mt-3">
        <thead>
            <tr>
                <th>ID</th>
                <th>Équipe Domicile</th>
                <th>Score</th>
                <th>Équipe Visiteur</th>
            </tr>
        </thead>
        <tbody>
            {% for match in matchs %}
            <tr>
                <td>{{ match.id_match }}</td>
                <td>{{ match.equipe_domicile.nom }}</td>
                <td>{{ match.buts_domicile }} - {{ match.buts_exterieur }}</td>
                <td>{{ match.equipe_exterieur.nom }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">Aucun match disponible.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'creer_match' %}" class="btn btn-primary mt-3">Ajouter un Match</a>
</body>
</html>

defidev/tournois_foot/templates/creer_equipe.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}API Foot{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% include 'includes/navbar.html' %}

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    <div class="container mt-5">
        <h1>Créer une nouvelle équipe</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Créer l'équipe</button>
        </form>
    </div>
</body>
</html>

defidev/tournois_foot/templates/creer_joueur.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}API Foot{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="container mt-4">
    {% include 'includes/navbar.html' %}

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    <div class="container mt-5">
        <h1>Créer un nouveau joueur</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_nom">Nom :</label>
                {{ form.nom }}
            </div>
            <div class="form-group">
                <label for="id_poste">Poste :</label>
                {{ form.poste }}
            </div>
            <div class="form-group">
                <label for="id_equipe">Équipe :</label>
                {{ form.equipe }}
            </div>
            <button type="submit" class="btn btn-primary">Créer le joueur</button>
        </form>
        <a href="{% url 'joueur_liste' %}" class="btn btn-secondary mt-3">Voir la liste des joueurs</a>
    </div>
</body>
</html>

defidev/tournois_foot/templates/creer_match.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}API Foot{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="container mt-4">
    {% include 'includes/navbar.html' %}

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    <h2>Créer un Match</h2>
    <form method="post" class="mt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Ajouter Match</button>
    </form>
    <a href="{% url 'classement' %}" class="btn btn-secondary mt-3">Voir le Classement</a>
</body>
</html>

defidev/tournois_foot/templates/equipe_liste.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}API Foot{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="container mt-4">
    {% include 'includes/navbar.html' %}

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    <div class="container mt-5">
        <h1>Liste des équipes</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Ville</th>
                </tr>
            </thead>
            <tbody>
                {% for equipe in equipes %}
                    <tr>
                        <td>{{ equipe.nom }}</td>
                        <td>{{ equipe.ville }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'creer_equipe' %}" class="btn btn-primary">Créer une équipe</a>
    </div>
</body>
</html>

defidev/tournois_foot/templates/joueur_liste.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}API Foot{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% include 'includes/navbar.html' %}

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    <div class="container mt-5">
        <h1>Liste des joueurs</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Poste</th>
                    <th>Équipe</th>
                </tr>
            </thead>
            <tbody>
                {% for joueur in joueurs %}
                    <tr>
                        <td>{{ joueur.nom }}</td>
                        <td>{{ joueur.poste }}</td>
                        <td>{{ joueur.equipe.nom }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'creer_joueur' %}" class="btn btn-primary">Ajouter un joueur</a>
    </div>
</body>
</html>

defidev/tournois_foot/templates/recherche.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}API Foot{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% include 'includes/navbar.html' %}

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    <h2>Recherche avancée</h2>
    <form method="get">
        <input type="text" name="q" placeholder="Rechercher une équipe ou un joueur..." value="{{ query }}">
        <button type="submit">Rechercher</button>
    </form>

    {% if results %}
        <h2>Résultats pour "{{ query }}"</h2>
        <h3>Équipes</h3>
        <ul>
            {% for equipe in results.equipes %}
                <li>{{ equipe.nom }} - {{ equipe.ville }}</li>
            {% empty %}
                <li>Aucune équipe trouvée.</li>
            {% endfor %}
        </ul>

        <h3>Joueurs</h3>
        <ul>
            {% for joueur in results.joueurs %}
                <li>{{ joueur.nom }} - Poste : {{ joueur.poste }} (Équipe : {{ joueur.equipe_nom }})</li>
            {% empty %}
                <li>Aucun joueur trouvé.</li>
            {% endfor %}
        </ul>
    {% endif %}
</body>
</html>